fix: fix finally block not executed
snapshot-labs/pineapple pull request #170
Opened 2023-09-05 02:45 UTC by wa0x6e

## Fix

Fix the `finally` not being executed due to error thrown inside catch block. Fixed by returning  a `Promise.reject` instead

## Chores

- Add `status` label to `ipfs_gateways_response_duration_seconds` and `providers_upload_duration_seconds` metrics => differentiate metrics for requests that succeed/failed

2023-09-05 08:39 UTC, Todmy requested changes

2023-09-05 08:39 UTC, Todmy commented on src/providers/index.ts
> +        return Promise.reject(e);
it's strange. For this case `throw e;` behaves the same as `return Promise.reject(e);`. And in both cases, the `finally` block will be called

2023-09-05 14:33 UTC, wa0x6e commented on src/providers/index.ts
> +        return Promise.reject(e);
Seems like it's not the case, test it with this code 

```
Promise.any(
  [0, 1, 2].map(i => {
    try {
      console.log(i);
      throw new Error('Oops');
    } catch (e) {
      throw e;
      // return Promise.reject(e);
    } finally {
      console.log('Ending ', i);
    }
  })
);
```

2023-09-06 08:27 UTC, Todmy approved these changes
tACK

2023-09-06 08:27 UTC, Todmy commented on src/providers/index.ts
> +        return Promise.reject(e);
it makes sense. Thank you for explanation

2023-09-06 08:30 UTC, merged