chore: upgrade to snapshot-metrics 1.4.0
snapshot-labs/pineapple pull request #180
Opened 2023-09-11 10:58 UTC by wa0x6e

## Changes 

- Update snapshot-sentry to latest (add support for JSON-RPC error)
- Update snapshot-metrics to latest (add support for pushgateway, and embedded `express_open_connections_size` metrics)

2023-09-12 08:11 UTC, Todmy requested changes

2023-09-12 08:11 UTC, Todmy commented on src/metrics.ts
> +    whitelistedPath: [/^\/$/, /^\/upload$/, /^\/ipfs\/.*$/],
why do we need this line? What paths do you want to omit?

2023-09-12 11:29 UTC, wa0x6e commented on src/metrics.ts
> +    whitelistedPath: [/^\/$/, /^\/upload$/, /^\/ipfs\/.*$/],
Everything not caught by the regex

2023-09-13 10:07 UTC, Todmy commented on src/metrics.ts
> +    whitelistedPath: [/^\/$/, /^\/upload$/, /^\/ipfs\/.*$/],
Which routes do we have here except `/`, `/upload` and `/ipfs`?

2023-09-13 10:08 UTC, Todmy requested changes

2023-09-13 10:08 UTC, Todmy commented on src/metrics.ts
> +    whitelistedPath: [/^\/$/, /^\/upload$/, /^\/ipfs\/.*$/],
Which routes do we have here except `/`, `/upload` and `/ipfs`?

2023-09-13 16:13 UTC, wa0x6e commented on src/metrics.ts
> +    whitelistedPath: [/^\/$/, /^\/upload$/, /^\/ipfs\/.*$/],
None. It's to avoid catching the fallback routes

2023-09-14 10:27 UTC, Todmy approved these changes
utACK

2023-09-15 13:11 UTC, merged